name: Git auto push
on:
  push:
  workflow_dispatch:
  schedule:
    - cron : '1 0 * * *'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Update
        run: |
          node index.js
      - name: commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: yhassanige1
          author_email: yanny.hassani@universite-paris-saclay.fr
          force: false
          signoff: false
          message: 'add this hit'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
