name: Git auto push
on:
  push:
  workflow_dispatch:
  schedule:
    - cron : '13 1 * * *'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Update
        run: |
          node index.js
      - name: Add and Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          add: .
          message: Automatic commit
      - name: Push changes
        run: |
          git config --global user.email "yanny.hassani@universite-paris-saclay.fr"
          git config --global user.name "yhassanige1"
          git push